### ISSUE TITLE
module 'cmp' not found

### ISSUE THREAD

**Issue by darkseid-is** [magicalne/nvim.ai#10]
Is nvim-cmp a required dependency ?

**Comment by magicalne** [comment]
No, cmp is optional. It simply provides convenience with keyword autocomplete, like `/system`, `/you`, `/buf`.

By the way, which completion plugin are you using?

**Comment by darkseid-is** [comment]
I don't use any completion plugin

**Comment by magicalne** [comment]
Then you need to specify bufnr manually:
```
/you

/buf 1
/buf 2

{{your_prompt}}
```

**Comment by darkseid-is** [comment]
Opening nvim after installing this plugin throws this error.
