### ISSUE TITLE
nvim-cmp piece does not work.

### ISSUE THREAD

**Issue by codr1** [magicalne/nvim.ai#32]
I added the nvim-cmp config, and ti does not work.
```
    {
        "hrsh7th/nvim-cmp",
        opts = function()
            local cmp = require "cmp"
            local conf = require "nvchad.configs.cmp"
            cmp.setup {
                mapping = {
                    sources = cmp.config.sources {
                        { name = "nvimai_cmp_source" }, -- This is optional but recommended
                    },
                },
            }
            conf.mapping = {
                -- this little section is just for nvim.ai
                --sources = cmp.config.sources {
                --    { name = "nvimai_cmp_source" }, -- This is optional but recommended
                --},
                ["<Up>"] = cmp.mapping.select_prev_item(),
                ["<Down>"] = cmp.mapping.select_next_item(),
                ["<Enter>"] = cmp.mapping.confirm {
                    behavior = cmp.ConfirmBehavior.Replace,
                    select = true,
                },
            }
            return conf
        end,
    },
```
The moment I type : in normal mode, I get errors

![image](https://github.com/user-attachments/assets/c7d6d296-0163-4b74-882e-1e13059ccadd)

**Comment by magicalne** [comment]
I made some update last week but forgot to update the docs. You don't need to specify cmp source in your config. It should work if you have cmp installed.

**Comment by jakubdonovan** [comment]
> I made some update last week but forgot to update the docs. You don't need to specify cmp source in your config. It should work if you have cmp installed.

I don't seem to get suggestions either. Supermaven worked fine though. Is there an error in my configuration?
![Screenshot 2024-09-15 at 13 42 27](https://github.com/user-attachments/assets/05f35b79-7cff-4f9d-9b27-fc8c8b2b491d)

**Comment by magicalne** [comment]
May I ask does the chat work? Can you send request to your LLM?
```md
/you

Hi?
```
Can you see any response after pressing <kbd>Enter</kbd>?

---

I think there might be some misunderstanding here. This is not an autocomplete plugin. Therefore, you can't type your code and expect it to be autocompleted by cmp. This plugin is designed to help you set up context and polish your prompt in the chat. It also allows you to insert or rewrite your code based on the chat history.

**Comment by jakubdonovan** [comment]
> May I ask does the chat work? Can you send request to your LLM?
> 
> ```
> /you
> 
> Hi?
> ```
> 
> Can you see any response after pressing Enter?
> 
> I think there might be some misunderstanding here. This is not an autocomplete plugin. Therefore, you can't type your code and expect it to be autocompleted by cmp. This plugin is designed to help you set up context and polish your prompt in the chat. It also allows you to insert or rewrite your code based on the chat history.

Thanks for getting back to me! To answer your question - yes, I get a response. 
![Screenshot 2024-09-15 at 14 12 51](https://github.com/user-attachments/assets/2458bcfc-2719-4398-b23c-bf6ab0e97bea)

As for autocomplete suggestions, I thought that this plugin would do it as it integrates into cmp yet I have never seen it give me cmp suggestions

**Comment by magicalne** [comment]
Haha, no. It doesn't work that way.
The cmp only autocompletes some keywords like `/you` and slash commands like `/buf` in the chat buffer.

I wrote a [post](https://magicalne.github.io/posts/why_autocomplete_with_llm_is_a_bad_idea/) about why autocomplete is a bad idea. You can read it if you want to spend more time on this topic.

Recently I'm planing to add a feature about `autocomplete`. It's inspired by `tab flow` from cursor. You might be interested in [avante.nvim](https://github.com/yetone/avante.nvim). It supports `tab flow` with sonnet 3.5 already.

**Comment by jakubdonovan** [comment]
> Haha, no. It doesn't work that way. The cmp only autocompletes some keywords like `/you` and slash commands like `/buf` in the chat buffer.
> 
> I wrote a [post](https://magicalne.github.io/posts/why_autocomplete_with_llm_is_a_bad_idea/) about why autocomplete is a bad idea. You can read it if you want to spend more time on this topic.
> 
> Recently I'm planing to add a feature about `autocomplete`. It's inspired by `tab flow` from cursor. You might be interested in [avante.nvim](https://github.com/yetone/avante.nvim). It supports `tab flow` with sonnet 3.5 already.

Can you think of a reason why this wouldn't work? 
![Screenshot 2024-09-16 at 12 05 15](https://github.com/user-attachments/assets/39eb37b5-f615-4e49-af02-260bab0621b2)

**Comment by magicalne** [comment]
This is the correct version:
```md
/you
/buf 25
/buf 1
{your_prompt}
```
The sidebar is divided into blocks. When a line starts with `/you` that means the next block is a message of user, where you can setup context. You should setup buffers after `/you`. And create your prompt in a new line. In your case, there is no message at all.

You can checkout demos for more details.

**Comment by jakubdonovan** [comment]
> This is the correct version:
> 
> ```
> /you
> /buf 25
> /buf 1
> {your_prompt}
> ```
> 
> The sidebar is divided into blocks. When a line starts with `/you` that means the next block is a message of user, where you can setup context. You should setup buffers after `/you`. And create your prompt in a new line. In your case, there is no message at all.
> 
> You can checkout demos for more details.

Thanks, that did it

**Comment by jakubdonovan** [comment]
> This is the correct version:
> 
> ```
> /you
> /buf 25
> /buf 1
> {your_prompt}
> ```
> 
> The sidebar is divided into blocks. When a line starts with `/you` that means the next block is a message of user, where you can setup context. You should setup buffers after `/you`. And create your prompt in a new line. In your case, there is no message at all.
> 
> You can checkout demos for more details.

I provided it with two .ts files for context and asked it to write me a function but it gave me python code. Are there any extra steps I need to take with the system prompt to make it content aware?
![Screenshot 2024-09-16 at 12 59 27](https://github.com/user-attachments/assets/87c8d3f1-a2dd-44c6-8196-4b58bf45ca0d)

**Comment by magicalne** [comment]
> EDIT: Silly mistake, this was the prompt I wrote before restarting my neovim instance so the buffers were no longer valid despite me having reopened the same files. Do you reckon it would be wise to implement a check before a prompt is sent to the LLM to prevent wasting tokens?

Yeah, `validate buffnr before sending request` is a good advise. I'll do it.

**Comment by jakubdonovan** [comment]
> > EDIT: Silly mistake, this was the prompt I wrote before restarting my neovim instance so the buffers were no longer valid despite me having reopened the same files. Do you reckon it would be wise to implement a check before a prompt is sent to the LLM to prevent wasting tokens?
> 
> Yeah, `validate buffnr before sending request` is a good advise. I'll do it.

Is it possible limit nvim.ai cmp to the chat buffer so that it doesn't show the chat commands everywhere else?

![Screenshot 2024-09-16 at 13 59 43](https://github.com/user-attachments/assets/ead6f11b-4678-4e4b-bf73-b105d7ae1f57)

**Comment by magicalne** [comment]
I think so. It should be activated on sidebar only. I'll take a look later on.

**Comment by magicalne** [comment]
Just made some updates on your suggestions:
- validate buffer numbers before sending request
- cmp keywords only works in the sidebar

**Comment by codr1** [comment]
(hey guys - been a slammed couple of weeks.  appreciate the updates.  will check as soon as I get a breather)
